import type {
  Asset,
  Inventory,
  InventoryStockEntry,
  StockItem,
  StockItemHistoryEntry,
} from "./assetTypes";

export const defaultInventories: Inventory[] = [
  {
    id: "inv-1",
    name: "Summer Conference 2026",
    event: "Annual Tech Summit",
    description: "AV equipment and stage materials for the summer conference",
    date: "2026-07-15",
    color: "#6366f1",
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "inv-2",
    name: "Product Launch Q2",
    event: "Product Launch Event",
    description: "Displays, lighting, and booth materials for the Q2 launch",
    date: "2026-05-20",
    color: "#ec4899",
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "inv-3",
    name: "Office General",
    event: "Permanent Assets",
    description: "All permanent office equipment and furniture",
    date: "",
    color: "#22c55e",
    createdAt: "2025-12-01T08:00:00Z",
  },
];

export const defaultAssets: Asset[] = [
  {
    id: "a-1",
    name: "Sony 4K Projector",
    photo: "",
    category: "AV Equipment",
    serialNumber: "SNY-4K-00123",
    assignedTo: "Marcus Johnson",
    condition: "excellent",
    purchaseDate: "2025-11-01",
    purchasePrice: 2400,
    location: "Storage Room A",
    notes: "Includes carrying case and 2 spare bulbs",
    inventoryId: "inv-1",
    status: "available",
    createdAt: "2025-11-05T10:00:00Z",
    tags: ["AV", "projection"],
  },
  {
    id: "a-2",
    name: "Yamaha PA System",
    photo: "",
    category: "Audio",
    serialNumber: "YMH-PA-00456",
    assignedTo: "Sarah Chen",
    condition: "good",
    purchaseDate: "2025-09-15",
    purchasePrice: 1800,
    location: "Storage Room A",
    notes: "2x speaker cabinets, 1 mixer, all cables included",
    inventoryId: "inv-1",
    status: "in-use",
    createdAt: "2025-09-20T10:00:00Z",
    tags: ["audio", "speakers"],
  },
  {
    id: "a-3",
    name: "LED Panel 200W",
    photo: "",
    category: "Lighting",
    serialNumber: "LED-200W-0078",
    assignedTo: "Marcus Johnson",
    condition: "excellent",
    purchaseDate: "2026-01-20",
    purchasePrice: 560,
    location: "Warehouse B",
    notes: "Set of 4 panels",
    inventoryId: "inv-2",
    status: "available",
    createdAt: "2026-01-25T10:00:00Z",
    tags: ["lighting"],
  },
  {
    id: "a-4",
    name: "Display Monitor 27\"",
    photo: "",
    category: "Display",
    serialNumber: "DEL-27-00891",
    assignedTo: "Lisa Park",
    condition: "good",
    purchaseDate: "2025-08-10",
    purchasePrice: 450,
    location: "Office",
    notes: "Dell UltraSharp",
    inventoryId: "inv-3",
    status: "in-use",
    createdAt: "2025-08-15T10:00:00Z",
    tags: ["display", "office"],
  },
  {
    id: "a-5",
    name: "MacBook Pro 14\"",
    photo: "",
    category: "Computer",
    serialNumber: "APL-MBP-01234",
    assignedTo: "David Kim",
    condition: "excellent",
    purchaseDate: "2025-12-01",
    purchasePrice: 2499,
    location: "Office",
    notes: "M3 Pro chip, 18GB RAM",
    inventoryId: "inv-3",
    status: "in-use",
    createdAt: "2025-12-05T10:00:00Z",
    tags: ["computer", "laptop"],
  },
  {
    id: "a-6",
    name: "Canon EOS R5 Camera",
    photo: "",
    category: "Camera",
    serialNumber: "CAN-R5-00567",
    assignedTo: "Emily Torres",
    condition: "excellent",
    purchaseDate: "2026-02-10",
    purchasePrice: 3899,
    location: "Media Closet",
    notes: "With 24-70mm lens and 2 batteries",
    inventoryId: "inv-2",
    status: "available",
    createdAt: "2026-02-15T10:00:00Z",
    tags: ["camera", "photography"],
  },
  {
    id: "a-7",
    name: "Portable Stage Platform",
    photo: "",
    category: "Stage",
    serialNumber: "STG-PLT-00234",
    assignedTo: "Marcus Johnson",
    condition: "fair",
    purchaseDate: "2024-06-15",
    purchasePrice: 1200,
    location: "Warehouse B",
    notes: "8 modular sections, needs minor repair on section 3",
    inventoryId: "inv-1",
    status: "maintenance",
    createdAt: "2024-06-20T10:00:00Z",
    tags: ["stage", "furniture"],
  },
  {
    id: "a-8",
    name: "Wireless Microphone Set",
    photo: "",
    category: "Audio",
    serialNumber: "SHR-WL-00345",
    assignedTo: "Sarah Chen",
    condition: "good",
    purchaseDate: "2025-10-05",
    purchasePrice: 890,
    location: "Storage Room A",
    notes: "Shure BLX288/PG58 dual set",
    inventoryId: "inv-1",
    status: "available",
    createdAt: "2025-10-10T10:00:00Z",
    tags: ["audio", "wireless"],
  },
];

export const defaultStockItems: StockItem[] = [
  {
    id: "s-1",
    name: "Folding Tables",
    category: "Furniture",
    sku: "TBL-FOLD-6FT",
    description: "6ft rectangular folding tables",
    totalQuantity: 50,
    unit: "pcs",
    notes: "Stored in Warehouse B",
    createdAt: "2025-01-01T08:00:00Z",
    updatedAt: "2025-01-01T08:00:00Z",
    updatedBy: "System",
  },
  {
    id: "s-2",
    name: "Folding Chairs",
    category: "Furniture",
    sku: "CHR-FOLD-STD",
    description: "Standard padded folding chairs",
    totalQuantity: 200,
    unit: "pcs",
    notes: "Stack of 10 per bundle",
    createdAt: "2025-01-01T08:00:00Z",
    updatedAt: "2025-01-01T08:00:00Z",
    updatedBy: "System",
  },
  {
    id: "s-3",
    name: "Extension Cords (10m)",
    category: "Electrical",
    sku: "EXT-10M-3PIN",
    description: "10-meter 3-pin extension cords",
    totalQuantity: 30,
    unit: "pcs",
    notes: "Heavy duty, outdoor safe",
    createdAt: "2025-01-01T08:00:00Z",
    updatedAt: "2025-01-01T08:00:00Z",
    updatedBy: "System",
  },
  {
    id: "s-4",
    name: "Tablecloths",
    category: "Linens",
    sku: "TCL-6FT-WHT",
    description: "White tablecloths for 6ft tables",
    totalQuantity: 100,
    unit: "pcs",
    notes: "Machine washable polyester",
    createdAt: "2025-01-01T08:00:00Z",
    updatedAt: "2025-01-01T08:00:00Z",
    updatedBy: "System",
  },
  {
    id: "s-5",
    name: "Name Badge Holders",
    category: "Stationery",
    sku: "NBH-LNY-CLR",
    description: "Clear name badge holders with lanyards",
    totalQuantity: 500,
    unit: "pcs",
    notes: "Box of 100",
    createdAt: "2025-01-01T08:00:00Z",
    updatedAt: "2025-01-01T08:00:00Z",
    updatedBy: "System",
  },
  {
    id: "s-6",
    name: "Power Strips (6 outlet)",
    category: "Electrical",
    sku: "PWR-6OTL-SRG",
    description: "6-outlet surge-protected power strips",
    totalQuantity: 20,
    unit: "pcs",
    notes: "Surge protection, 2m cord",
    createdAt: "2025-01-01T08:00:00Z",
    updatedAt: "2025-01-01T08:00:00Z",
    updatedBy: "System",
  },
  {
    id: "s-7",
    name: "Projector Screens",
    category: "AV",
    sku: "SCR-100IN-TRP",
    description: "100-inch tripod projector screens",
    totalQuantity: 8,
    unit: "pcs",
    notes: "Portable, with carry bag",
    createdAt: "2025-01-01T08:00:00Z",
    updatedAt: "2025-01-01T08:00:00Z",
    updatedBy: "System",
  },
  {
    id: "s-8",
    name: "Microphone Stands",
    category: "Audio",
    sku: "MIC-STD-BLK",
    description: "Adjustable boom microphone stands",
    totalQuantity: 15,
    unit: "pcs",
    notes: "Heavy base, adjustable boom",
    createdAt: "2025-01-01T08:00:00Z",
    updatedAt: "2025-01-01T08:00:00Z",
    updatedBy: "System",
  },
];

export const defaultStockItemHistory: StockItemHistoryEntry[] = defaultStockItems.map((item) => ({
  id: `hist-${item.id}-created`,
  stockItemId: item.id,
  action: "created",
  changedAt: item.createdAt,
  changedBy: item.updatedBy || "System",
  summary: `Created with ${item.totalQuantity} ${item.unit}`,
}));

export const defaultInventoryStockEntries: InventoryStockEntry[] = [
  {
    id: "ise-1",
    inventoryId: "inv-1",
    stockItemId: "s-1",
    quantityBrought: 10,
    notes: "For speaker tables and registration",
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "ise-2",
    inventoryId: "inv-1",
    stockItemId: "s-2",
    quantityBrought: 80,
    notes: "Audience seating",
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "ise-3",
    inventoryId: "inv-1",
    stockItemId: "s-3",
    quantityBrought: 5,
    notes: "Stage and AV area power",
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "ise-4",
    inventoryId: "inv-1",
    stockItemId: "s-7",
    quantityBrought: 2,
    notes: "Main stage and breakout room",
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "ise-5",
    inventoryId: "inv-1",
    stockItemId: "s-8",
    quantityBrought: 6,
    notes: "Speakers and Q&A",
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "ise-6",
    inventoryId: "inv-2",
    stockItemId: "s-1",
    quantityBrought: 5,
    notes: "Demo and display tables",
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "ise-7",
    inventoryId: "inv-2",
    stockItemId: "s-2",
    quantityBrought: 40,
    notes: "Guest seating",
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "ise-8",
    inventoryId: "inv-2",
    stockItemId: "s-5",
    quantityBrought: 100,
    notes: "Guest name badges",
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "ise-9",
    inventoryId: "inv-2",
    stockItemId: "s-4",
    quantityBrought: 20,
    notes: "Display table coverings",
    createdAt: "2026-02-01T10:00:00Z",
  },
];
